version: '3'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=reallyStrongPwd123
    ports:
      - "1433:1433"
  web:
    build: .
    ports:
     - "5000:5000"